### PR TITLE
Update all packages to latest

### PR DESCRIPTION
**Pull request by Cellule**
Transition to scss for bootstrap
Begin transition to css module for styling (maybe scss would be a better option... will see when I decide to actually kill off remaining less stylesheets)

I think there a slight regression in styling on small devices

## Before
image

## After
image

---
This change is [Reviewable](https://reviewable.io/reviews/cellule/dndgenerator/54)

### CODE REVIEW

**Comment by etiens** [comment]
The website currently has 4 configurations.
This particular configuration didn't seem to enjoy the changes:

We could probably remove this configuration if fixing it would be too complicated.

**Comment by Cellule** [comment]
Which browser was that? I started looking a bit more on smaller viewport already. I got few fixes pending. I'll triole check this one tobight and update accordingly

**Comment by etiens** [comment]
I was able to reproduce in both Firefox and Chrome, when the window is resized to take up about 60% of the width of my screen.

________________________________

**Comment by Cellule** [comment]
Are you sure you are running on my branch with everything updated ? 
Cause I'm actually seeing this problem on live npcgenerator.com but not on my branch

## Live
image

## Responsiveness on this branch


https://user-images.githubusercontent.com/4157103/145698469-bcd76e40-7b18-47d8-a5a9-e44e8443fdf2.mp4

**Comment by etiens** [comment]
My bad, I was on your new branch but hadn’t run npm install!

It does work perfectly now, thank you!

**Pull request merged**
